### PR TITLE
Fix setting dimension for opened/attached dialog

### LINKED ISSUE #156: setWidth/setHeight not working if dialog is attached
After #147, when the dialog is attached and/or opened, calls to `setWidth` and `setHeight` will not work as expected.

This bug behaves differently depending on the mode the dialog is opened:
- If self attached, calls to `setWidth` and `setHeight` won't work while the dialog is opened
- If dialog is explicitly attached, calls to `setWidth` and `setHeight` won't work after dialog is attached

### PR DESCRIPTION
**Pull request by DiegoCardoso**
- Make call to set overlay dimension on setWidth/setHeight
- Add tests to cover cases the bug was present

Fixes #156

### CODE REVIEW

File: vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java [hunk 1]
```diff
@@ -139,11 +139,13 @@ public String getHeight() {
     @Override
     public void setWidth(String value) {
         width = value;
+        setDimension(ElementConstants.STYLE_WIDTH, value);
```
Comment (tomivirkki) [inline vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java]: Now that the API also updates the Web Component dimensions, the internal `resizeListener` should no longer use it but instead just update the `width` and `height` fields directly. Otherwise, users with slow connection will experience weird jumpy behavior.

File: vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java [hunk 2]
```diff
@@ -566,6 +568,11 @@ public Registration addDetachListener(
         return super.addDetachListener(listener);
     }
 
+    private void setDimension(String dimension, String value) {
+        getElement()
+            .executeJs("this.$.overlay.$.overlay.style."+dimension+"=$0", value);
```
Comment (tomivirkki) [inline vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java]: This could be aligned as: `getElement().executeJs("this.$.overlay.$.overlay.style[$0]=$1", dimension, value);`

File: vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java (hunk 1 above)
Comment (DiegoCardoso) [reply vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java]: Change `resizeListener` to set properties instead.

File: vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java (hunk 2 above)
Comment (DiegoCardoso) [reply vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java]: Changed as suggested.
