### PR TITLE
fix the buttons in the confirmation dialog demo

### LINKED ISSUE #143: Confirmation dialog demo: replace NativeButton with Button
It turns out https://vaadin.com has CSS reset for `<button>` element (which removes backrgound and border). The demo looks weird because of that.

dialog

Let's consider using `Button` instead of `NativeButton` for this demo.

### PR DESCRIPTION
**Pull request by shadikhani**
Fix #143

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-dialog-flow/145)

### CODE REVIEW

File: vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java [hunk 1]
```diff
@@ -67,7 +68,7 @@ private void addBasicDialog() {
     }
 
     private void addConfirmationDialog() {
-        NativeButton button = new NativeButton(BUTTON_CAPTION);
+        Button button = new Button(BUTTON_CAPTION);
```
Comment (web-padawan) [inline vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java]: You can keep this button unchanged. Only the buttons in the dialog need to be updated.

Comment (shadikhani) [reply vaadin-dialog-flow-demo/src/main/java/com/vaadin/flow/component/dialog/demo/DialogView.java]: Done.
