### PR TITLE
fix: prevent showing scrollbar when content fits

### LINKED ISSUE #225: Vaadin 17: Wrong dialog size
We are using a `VertiacalLayout`, without the `padding` theme, inside a dialog. The `VerticalLayout` contains a title, a body and a button.
Since we upgraded to Vaadin 17, this dialog shows a vertical scrollbar:
Vaadin 14:
image
Vaadin 17:
image

The issue seems to be related to #195. The [`display: inline`of the draggable-div](https://github.com/vaadin/vaadin-dialog-flow/blob/master/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L66) seems to cause an additional space at the top of the dialog, which causes it to display the scrollbar.

Reproduction:

1. Create a new Vaadin 17 Project
2. Create a view with the following content:
```
	Dialog dlg = new Dialog();
	VerticalLayout vl = new VerticalLayout();
	vl.setPadding(false);
	vl.add(new Span("Title"));
	vl.add(new Span("Body"));
	vl.add(new Button("OK"));
	dlg.add(vl);
	Button button = new Button("Open dialog", e -> dlg.open());
	add(button);
```
3. Execute the project and click the button to open the dialog.

### PR DESCRIPTION
**Pull request by DiegoCardoso**
Previously, a fix was introduced to prevent vertical scrollbar from showing when content had margin due some margin collapse, so the fix was to force the container to be `inline-block`. This caused a regression for, eg. a VerticalLayout with no padding, which now makes visible scrollbar.

This change makes the internal container to be a flex box with column direction.

Fixes #225

### CODE REVIEW

File: vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java [hunk 1]
```diff
@@ -68,7 +68,8 @@ public Dialog() {
         container.getClassList().add("draggable-leaf-only");
         container.getStyle().set(ElementConstants.STYLE_WIDTH, "100%");
         container.getStyle().set(ElementConstants.STYLE_HEIGHT, "100%");
-        container.getStyle().set("display", "inline-block");
+        container.getStyle().set("display", "flex");
+        container.getStyle().set("flex-direction", "column");
```
Comment (tomivirkki) [inline vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java:72]: This causes a (breaking) change for the layout: The "Confirmation dialog" demo buttons align differently (on top of each other) after the change:
Screenshot 2020-09-30 at 9 38 50

**Review by tomivirkki — CHANGES_REQUESTED** [review]

File: vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java (hunk 1 above)
Comment (tomivirkki) [reply vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java:72]: ...it depends on the type of the items. Block elements should layout on top of each other so flexbox might be problematic.

Comment (DiegoCardoso) [reply vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java:72]: Yeah. I was thinking about that late yesterday. Using `flex`, we will either force block elements to align next to each other (`flex-direction: row`) or inline elements to align on top of each other (`flex-direction: column`).

Comment (tomivirkki) [reply vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java:72]: So are there some alternatives to using flex for the container? Or would it fix the issue to make the parent flow-component-renderer element a flexbox?

Comment (DiegoCardoso) [reply vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java]: I started trying to apply changes to `flow-component-renderer`. Now trying to set `flex` there. It looks as it is working locally. Please, take a look.

**Review by tomivirkki — APPROVED** [review]
